//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class drinkshopEntities2 : DbContext
    {
        public drinkshopEntities2()
            : base("name=drinkshopEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<drink> drinks { get; set; }
    
        public virtual int drinkDelete(Nullable<int> drinkid)
        {
            var drinkidParameter = drinkid.HasValue ?
                new ObjectParameter("drinkid", drinkid) :
                new ObjectParameter("drinkid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("drinkDelete", drinkidParameter);
        }
    
        public virtual int drinkEdit(Nullable<int> drinkid, Nullable<bool> istoppings, string toppingsname, string sugerlevel, string icelevel)
        {
            var drinkidParameter = drinkid.HasValue ?
                new ObjectParameter("drinkid", drinkid) :
                new ObjectParameter("drinkid", typeof(int));
    
            var istoppingsParameter = istoppings.HasValue ?
                new ObjectParameter("istoppings", istoppings) :
                new ObjectParameter("istoppings", typeof(bool));
    
            var toppingsnameParameter = toppingsname != null ?
                new ObjectParameter("toppingsname", toppingsname) :
                new ObjectParameter("toppingsname", typeof(string));
    
            var sugerlevelParameter = sugerlevel != null ?
                new ObjectParameter("sugerlevel", sugerlevel) :
                new ObjectParameter("sugerlevel", typeof(string));
    
            var icelevelParameter = icelevel != null ?
                new ObjectParameter("icelevel", icelevel) :
                new ObjectParameter("icelevel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("drinkEdit", drinkidParameter, istoppingsParameter, toppingsnameParameter, sugerlevelParameter, icelevelParameter);
        }
    
        public virtual int drinkInsert(Nullable<int> drinkid, string deinkname, Nullable<bool> istoppings, string toppingsname, string sugerlevel, string icelevel)
        {
            var drinkidParameter = drinkid.HasValue ?
                new ObjectParameter("drinkid", drinkid) :
                new ObjectParameter("drinkid", typeof(int));
    
            var deinknameParameter = deinkname != null ?
                new ObjectParameter("deinkname", deinkname) :
                new ObjectParameter("deinkname", typeof(string));
    
            var istoppingsParameter = istoppings.HasValue ?
                new ObjectParameter("istoppings", istoppings) :
                new ObjectParameter("istoppings", typeof(bool));
    
            var toppingsnameParameter = toppingsname != null ?
                new ObjectParameter("toppingsname", toppingsname) :
                new ObjectParameter("toppingsname", typeof(string));
    
            var sugerlevelParameter = sugerlevel != null ?
                new ObjectParameter("sugerlevel", sugerlevel) :
                new ObjectParameter("sugerlevel", typeof(string));
    
            var icelevelParameter = icelevel != null ?
                new ObjectParameter("icelevel", icelevel) :
                new ObjectParameter("icelevel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("drinkInsert", drinkidParameter, deinknameParameter, istoppingsParameter, toppingsnameParameter, sugerlevelParameter, icelevelParameter);
        }
    
        public virtual ObjectResult<drinkSelete_Result> drinkSelete(string drinkname)
        {
            var drinknameParameter = drinkname != null ?
                new ObjectParameter("drinkname", drinkname) :
                new ObjectParameter("drinkname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<drinkSelete_Result>("drinkSelete", drinknameParameter);
        }
    }
}
